apiVersion: apps/v1
kind: Deployment
metadata:
  name: financeapp
  namespace: finance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: financeapp
  template:
    metadata:
      labels:
        app: financeapp
    spec:
      containers:
      - name: financeapp
        image: zeeshancloud15/finaceapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
