apiVersion: v1
kind: Service

metadata:
  name: finaceapp-service
  namespace: finance

spec:
  type: NodePort

  selector:
    app: finaceapp

  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
