apiVersion: v1
kind: Service
metadata:
  name: financeapp-service
  namespace: financeapp
spec:
  type: NodePort

  selector:
    app: financeapp

  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
